import { createI18n } from 'vue-i18n';

interface MessagesShape {
  appTitle: string; calculation: string; scenarios: string; help: string; profile: string; costs: string; project: string; advanced: string; exchangeRate: string; reset: string; csv: string; results: string; applyChanges: string; method: string; noScenarios: string; scenariosSaved: string; rateBase: string; rateAdjusted: string; rateStrategic: string; priceProject: string; priceRetainer: string; marginRelative: string; updateFx: string;
  styleGuide?: string; styleGuideTitle?: string; componentsHeading?: string; typographyHeading?: string; usageHeading?: string; variantsHeading?: string;
  approxUSD?: string;
  // Field labels
  role: string; experience: string; marketLevel: string; currency: string; monthlyCost: string; productiveHoursWeek: string; weeksYear: string; billableUtilization: string; margin: string; projectHours: string; complexity: string; risk: string; businessValue: string; retainerHours: string;
  // Select option labels
  optRoleFrontend: string; optRoleBackend: string; optRoleFullstack: string; optRoleUiux: string; optRolePm: string; optMarketLocal: string; optMarketNearshore: string; optMarketUsEu: string; optMarketPremium: string; optComplexityLow: string; optComplexityMedium: string; optComplexityHigh: string; optComplexityVeryHigh: string; optRiskLow: string; optRiskMedium: string; optRiskHigh: string; optValueLow: string; optValueMedium: string; optValueHigh: string; optValueCritical: string;
  // Card subs & extra labels
  subBase: string; subAdjusted: string; subStrategic: string; subProject: string; subRetainer: string; subMargin: string; 
  // Panel descriptions
  descProfile: string; descCosts: string; descProject: string; descAdvanced: string; 
  // Method paragraphs
  methodBaseLine: string; methodAdjustedLine: string; methodStrategicLine: string; 
  // Scenario & tables
  scenarioNamePlaceholder: string; save: string; tableName: string; tableValueRate: string; tableProject: string; tableRetainer: string; compareHeader: string; loadingChart: string; emptyChart?: string;
  usdPerHour?: string; usdLabel?: string;
  notApplicable?: string;
  // Help section
  helpTitle: string; helpIntro: string; stepsTitle: string; tipsTitle: string; limitsTitle: string; step1: string; step2: string; step3: string; step4: string; tip1: string; tip2: string; tip3: string; tip4: string; limitsText: string; miniSimTitle?: string; miniSimDesc?: string; miniSimReset?: string; simNav?: string;
  // Help formula extra
  helpFormulaTitle?: string; helpVarsTitle?: string; helpVarMonthly?: string; helpVarProdHours?: string; helpVarWeeks?: string; helpVarUtil?: string; helpVarMargin?: string; helpVarExp?: string; helpFormulaBaseLabel?: string; helpFormulaAdjustedLabel?: string;
  // Tooltips
  tipRole: string; tipExperience: string; tipMarketLevel: string; tipCurrency: string; tipExchangeRate: string; tipMonthlyCost: string; tipProdHours: string; tipWeeksYear: string; tipUtilization: string; tipMargin: string; tipProjectHours: string; tipComplexity: string; tipRisk: string; tipBusinessValue: string; tipRetainerHours: string;
  // Card tooltips
  tipBaseHourly: string; tipAdjustedHourly: string; tipValueHourly: string; tipProjectPrice: string; tipRetainerPrice: string; tipMarginPercent: string; 
  // Advanced multiplier group tips
  tipGroupRole: string; tipGroupMarket: string; tipGroupComplexity: string; tipGroupRisk: string; tipGroupBusinessValue: string;
  vesSourceLabel: string; vesSourceOfficial: string; vesSourceParallel: string;
  fxOneUsd?: string; fxInverse?: string;
}

const messages = {
  es: {
  appTitle: 'Calculadora Tarifas Dev', calculation: 'Cálculo', scenarios: 'Escenarios', help: 'Ayuda', styleGuide:'Guía', styleGuideTitle:'Guía de Estilos', componentsHeading:'Componentes UI', typographyHeading:'Tipografía', usageHeading:'Uso', variantsHeading:'Variantes', profile: 'Perfil', costs: 'Costos', project: 'Proyecto', advanced: 'Ajustes avanzados', exchangeRate: 'Tipo de cambio', updateFx: 'Actualizar FX', reset: 'Reset', csv: 'CSV', results: 'Resultados', applyChanges: 'Aplicar cambios', method: 'Método de cálculo', noScenarios: 'No hay escenarios aún.', scenariosSaved: 'Escenarios Guardados', rateBase: 'Tarifa base', rateAdjusted: 'Tarifa ajustada', rateStrategic: 'Tarifa estratégica', priceProject: 'Precio proyecto', priceRetainer: 'Retainer mensual', marginRelative: 'Margen relativo', approxUSD: '≈ {value} USD', fxOneUsd: '1 USD = {value} {cur}', fxInverse: '1 {cur} = {value} USD',
    role: 'Rol principal', experience: 'Experiencia (años)', marketLevel: 'Nivel mercado', currency: 'Moneda', monthlyCost: 'Costo mensual vida', productiveHoursWeek: 'Horas productivas / semana', weeksYear: 'Semanas trabajadas / año', billableUtilization: '% Utilización facturable', margin: '% Margen deseado', projectHours: 'Esfuerzo estimado (horas)', complexity: 'Complejidad', risk: 'Riesgo', businessValue: 'Valor de negocio', retainerHours: 'Retainer (h/mes)',
    optRoleFrontend: 'Frontend', optRoleBackend: 'Backend', optRoleFullstack: 'Fullstack', optRoleUiux: 'UI/UX', optRolePm: 'PM', optMarketLocal: 'Local', optMarketNearshore: 'Nearshore', optMarketUsEu: 'US/EU', optMarketPremium: 'Premium', optComplexityLow: 'Baja', optComplexityMedium: 'Media', optComplexityHigh: 'Alta', optComplexityVeryHigh: 'Muy alta', optRiskLow: 'Bajo', optRiskMedium: 'Medio', optRiskHigh: 'Alto', optValueLow: 'Bajo', optValueMedium: 'Medio', optValueHigh: 'Alto', optValueCritical: 'Crítico',
    subBase: 'Sin factores estratégicos', subAdjusted: 'Mercado + rol + experiencia', subStrategic: 'Complejidad + riesgo + valor', subProject: 'Horas * tarifa estratégica * factor', subRetainer: '{hours}h incluidas', subMargin: 'vs base', descProfile: 'Rol y posicionamiento de mercado', descCosts: 'Estructura de costos base', descProject: 'Parámetros del engagement', descAdvanced: 'Edita multiplicadores', methodBaseLine: 'Base: (Costo mensual * 12) / (Horas productivas anuales * Utilización) * (1 + margen)', methodAdjustedLine: 'Ajustes por mercado, rol y experiencia: multiplicadores compuestos.', methodStrategicLine: 'Estrategia: factores de complejidad, riesgo y valor agregan prima.',
  scenarioNamePlaceholder: 'Nombre escenario', save: 'Guardar', tableName: 'Nombre', tableValueRate: 'Tarifa Estrat.', tableProject: 'Proyecto', tableRetainer: 'Retainer', compareHeader: 'Comparativa Escenarios', loadingChart: 'Cargando gráfica…', emptyChart: 'Agrega primero un escenario para ver la gráfica.', usdPerHour: 'USD/h', usdLabel: 'USD', notApplicable: '—',
  helpTitle: 'Ayuda & Metodología', helpIntro: 'Esta calculadora combina un modelo de cost-plus con ajustes de mercado y un componente heurístico de value based pricing. Úsalo como punto de partida.', stepsTitle: 'Pasos Clave', tipsTitle: 'Consejos', limitsTitle: 'Límites', step1: 'Define tus costos mensuales (incluye sueldo objetivo, SaaS, impuestos, etc.).', step2: 'Estima horas productivas y % de utilización facturable realista.', step3: 'Ajusta por mercado, rol y experiencia.', step4: 'Aplica factores de complejidad, riesgo y valor de negocio para capturar upside.', tip1: 'No subestimes vacaciones, feriados y tiempo improductivo.', tip2: 'El margen deseado debe cubrir reinversión, impuestos y riesgo.', tip3: 'Value pricing: incrementa precio si el impacto económico para el cliente es alto.', tip4: 'Usa escenarios para comparar condiciones (local vs US-EU, junior vs senior, etc.).', limitsText: 'No considera variaciones de tipo de cambio, inflación futura ni estructura fiscal compleja. Ajusta manualmente.', miniSimTitle: 'Mini Simulador', miniSimDesc: 'Modifica parámetros clave y observa cómo evolucionan las tarifas base, ajustada y estratégica en tiempo real.', miniSimReset: 'Reiniciar', simNav: 'Simulador',
  helpFormulaTitle: 'Fórmula Simplificada', helpVarsTitle: 'Variables', helpVarMonthly: 'Costo mensual: lo que necesitas ganar al mes (salario objetivo + gastos).', helpVarProdHours: 'Horas productivas por semana: horas realmente facturables.', helpVarWeeks: 'Semanas facturables: usamos 46 (descansos, vacaciones, improductivo).', helpVarUtil: 'Utilización: porcentaje de esas horas realmente vendidas.', helpVarMargin: 'Margen: extra para cubrir riesgo / profit.', helpVarExp: 'Multiplicador de experiencia: ajuste heurístico por seniority.', helpFormulaBaseLabel: 'baseHora', helpFormulaAdjustedLabel: 'tarifaAjustada',
    tipRole: 'Rol principal que determina expectativa de tarifa.', tipExperience: 'Años de experiencia profesional relevante.', tipMarketLevel: 'Mercado objetivo de los clientes (afecta disposición a pagar).', tipCurrency: 'Moneda en la que deseas ver los resultados.', tipExchangeRate: 'Tipo de cambio unidades de moneda seleccionada por 1 USD.', tipMonthlyCost: 'Costo mensual total: salario objetivo + gastos fijos + SaaS + impuestos + overhead.', tipProdHours: 'Horas realmente productivas por semana (descuenta reuniones, soporte, etc.).', tipWeeksYear: 'Semanas efectivas trabajadas al año (resta vacaciones/feriados).', tipUtilization: '% de horas productivas que realmente facturas.', tipMargin: 'Margen deseado sobre costo para reinversión, riesgo e impuestos.', tipProjectHours: 'Estimación de horas totales del proyecto (incluye gestión + QA).', tipComplexity: 'Complejidad técnica / incertidumbre de implementación.', tipRisk: 'Riesgo de cambios, dependencia externa o fallos críticos.', tipBusinessValue: 'Impacto económico o estratégico para el cliente.', tipRetainerHours: 'Horas incluidas mensualmente en un acuerdo recurrente.',
    tipBaseHourly: 'Tarifa base derivada de costos y utilización + margen.', tipAdjustedHourly: 'Tarifa base ajustada por mercado, rol y experiencia.', tipValueHourly: 'Tarifa estratégica tras aplicar complejidad, riesgo y valor.', tipProjectPrice: 'Precio recomendado para el alcance estimado (factor moderado).', tipRetainerPrice: 'Precio mensual con descuento por horas recurrentes.', tipMarginPercent: 'Prima relativa de la tarifa estratégica sobre la base.', tipGroupRole: 'Ajustes relativos entre roles (evita distorsiones extremas).', tipGroupMarket: 'Multiplicadores según poder adquisitivo / mercado objetivo.', tipGroupComplexity: 'Prima por incertidumbre técnica y carga cognitiva.', tipGroupRisk: 'Recargo por exposición a posibles retrabajos / fallos.', tipGroupBusinessValue: 'Captura valor económico generado para el cliente.',
    vesSourceLabel: 'Fuente VES', vesSourceOfficial: 'Oficial BCV', vesSourceParallel: 'Paralelo'
  },
  en: {
  appTitle: 'Dev Rates Calculator', calculation: 'Calculation', scenarios: 'Scenarios', help: 'Help', styleGuide:'Guide', styleGuideTitle:'Style Guide', componentsHeading:'UI Components', typographyHeading:'Typography', usageHeading:'Usage', variantsHeading:'Variants', profile: 'Profile', costs: 'Costs', project: 'Project', advanced: 'Advanced adjustments', exchangeRate: 'Exchange rate', updateFx: 'Update FX', reset: 'Reset', csv: 'CSV', results: 'Results', applyChanges: 'Apply changes', method: 'Calculation method', noScenarios: 'No scenarios yet.', scenariosSaved: 'Saved Scenarios', rateBase: 'Base rate', rateAdjusted: 'Adjusted rate', rateStrategic: 'Strategic rate', priceProject: 'Project price', priceRetainer: 'Monthly retainer', marginRelative: 'Relative margin', approxUSD: '≈ {value} USD', fxOneUsd: '1 USD = {value} {cur}', fxInverse: '1 {cur} = {value} USD',
    role: 'Primary role', experience: 'Experience (years)', marketLevel: 'Market level', currency: 'Currency', monthlyCost: 'Monthly cost (life)', productiveHoursWeek: 'Productive hrs / week', weeksYear: 'Working weeks / year', billableUtilization: 'Billable utilization %', margin: 'Desired margin %', projectHours: 'Estimated effort (hours)', complexity: 'Complexity', risk: 'Risk', businessValue: 'Business value', retainerHours: 'Retainer (h/mo)',
    optRoleFrontend: 'Frontend', optRoleBackend: 'Backend', optRoleFullstack: 'Fullstack', optRoleUiux: 'UI/UX', optRolePm: 'PM', optMarketLocal: 'Local', optMarketNearshore: 'Nearshore', optMarketUsEu: 'US/EU', optMarketPremium: 'Premium', optComplexityLow: 'Low', optComplexityMedium: 'Medium', optComplexityHigh: 'High', optComplexityVeryHigh: 'Very high', optRiskLow: 'Low', optRiskMedium: 'Medium', optRiskHigh: 'High', optValueLow: 'Low', optValueMedium: 'Medium', optValueHigh: 'High', optValueCritical: 'Critical',
    subBase: 'Without strategic factors', subAdjusted: 'Market + role + experience', subStrategic: 'Complexity + risk + value', subProject: 'Hours * strategic rate * factor', subRetainer: '{hours}h included', subMargin: 'vs base', descProfile: 'Role & market positioning', descCosts: 'Base cost structure', descProject: 'Engagement parameters', descAdvanced: 'Edit multipliers', methodBaseLine: 'Base: (Monthly cost * 12) / (Annual productive hours * Utilization) * (1 + margin)', methodAdjustedLine: 'Adjustments for market, role and experience: compounded multipliers.', methodStrategicLine: 'Strategy: complexity, risk and business value factors add premium.',
  scenarioNamePlaceholder: 'Scenario name', save: 'Save', tableName: 'Name', tableValueRate: 'Strategic Rate', tableProject: 'Project', tableRetainer: 'Retainer', compareHeader: 'Scenario Comparison', loadingChart: 'Loading chart…', emptyChart: 'Add a scenario first to display the chart.', usdPerHour: 'USD/h', usdLabel: 'USD', notApplicable: '—',
  helpTitle: 'Help & Methodology', helpIntro: 'This calculator blends a cost-plus model with market adjustments and a heuristic value based pricing component. Use it as a starting point.', stepsTitle: 'Key Steps', tipsTitle: 'Tips', limitsTitle: 'Limits', step1: 'Define your monthly costs (target salary, SaaS, taxes, etc.).', step2: 'Estimate productive hours and realistic billable utilization %.', step3: 'Adjust for market, role and experience.', step4: 'Apply complexity, risk and business value factors to capture upside.', tip1: 'Don\'t underestimate holidays and unproductive time.', tip2: 'Desired margin should cover reinvestment, taxes and risk.', tip3: 'Value pricing: raise price if client economic impact is high.', tip4: 'Use scenarios to compare conditions (local vs US-EU, junior vs senior, etc.).', limitsText: 'Does not account for FX volatility, future inflation or complex tax structures. Adjust manually.', miniSimTitle: 'Mini Simulator', miniSimDesc: 'Tweak key inputs and see base, adjusted and strategic rates update in real time.', miniSimReset: 'Reset', simNav: 'Simulator',
  helpFormulaTitle: 'Simplified Formula', helpVarsTitle: 'Variables', helpVarMonthly: 'Monthly cost: what you need to earn (target salary + expenses).', helpVarProdHours: 'Productive hours per week: truly billable hours.', helpVarWeeks: 'Billable weeks: we use 46 (time off, holidays, unproductive).', helpVarUtil: 'Utilization: percent of those hours you actually sell.', helpVarMargin: 'Margin: extra to cover risk / profit.', helpVarExp: 'Experience multiplier: heuristic seniority adjustment.', helpFormulaBaseLabel: 'baseRate', helpFormulaAdjustedLabel: 'adjustedRate',
    tipRole: 'Primary role influencing rate expectation.', tipExperience: 'Years of relevant professional experience.', tipMarketLevel: 'Target client market (affects willingness to pay).', tipCurrency: 'Currency to display results in.', tipExchangeRate: 'Exchange rate: selected currency units per 1 USD.', tipMonthlyCost: 'Total monthly cost: target salary + fixed expenses + SaaS + taxes + overhead.', tipProdHours: 'Truly productive hours per week (exclude meetings/support).', tipWeeksYear: 'Effective working weeks per year (minus vacation/holidays).', tipUtilization: 'Percent of productive hours you actually bill.', tipMargin: 'Desired margin over cost for reinvestment, risk and taxes.', tipProjectHours: 'Estimated total project hours (include management + QA).', tipComplexity: 'Technical complexity / implementation uncertainty.', tipRisk: 'Risk of changes, external dependencies or critical failures.', tipBusinessValue: 'Economic or strategic impact for the client.', tipRetainerHours: 'Hours included monthly in a recurring agreement.',
    tipBaseHourly: 'Base rate derived from costs, utilization and margin.', tipAdjustedHourly: 'Base rate adjusted by market, role and experience.', tipValueHourly: 'Strategic rate after complexity, risk and value factors.', tipProjectPrice: 'Recommended price for estimated scope (moderated factor).', tipRetainerPrice: 'Monthly price with discount for recurring hours.', tipMarginPercent: 'Relative premium of strategic over base rate.', tipGroupRole: 'Relative adjustments between roles (avoid extreme distortion).', tipGroupMarket: 'Multipliers by purchasing power / target market.', tipGroupComplexity: 'Premium for technical uncertainty and cognitive load.', tipGroupRisk: 'Surcharge for exposure to rework / failures.', tipGroupBusinessValue: 'Captures economic value generated for the client.',
    vesSourceLabel: 'VES source', vesSourceOfficial: 'Official BCV', vesSourceParallel: 'Parallel'
  }
} satisfies Record<'es'|'en', MessagesShape>;

export const i18n = createI18n<{ message: MessagesShape }, 'es' | 'en'>({
  legacy: false,
  locale: (localStorage.getItem('locale') as 'es' | 'en') || 'es',
  fallbackLocale: 'en',
  messages
});
